# Generated by Django 6.0.6 on 2026-06-13 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='entry_filename',
            field=models.CharField(default='sketch.js', help_text='Filename shown for the main source file.', max_length=100),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='code',
            field=models.TextField(help_text='Main sketch source code (entry point).'),
        ),
        migrations.CreateModel(
            name='SketchAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='e.g. particle.js', max_length=200)),
                ('content', models.TextField()),
                ('asset_type', models.CharField(choices=[('js', 'JavaScript'), ('css', 'CSS'), ('json', 'JSON'), ('other', 'Other')], default='js', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='sketches.sketch')),
            ],
            options={
                'ordering': ['order', 'filename'],
                'unique_together': {('sketch', 'filename')},
            },
        ),
    ]
