# Generated by Django 6.0.6 on 2026-06-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0002_sketch_entry_filename_alter_sketch_code_sketchasset'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='is_home_background',
            field=models.BooleanField(default=False, help_text='Use this sketch as the animated background on the home page.'),
        ),
    ]
