# Generated by Django 6.0.6 on 2026-07-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0007_sketch_fork_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='sketch',
            name='home_background_theme',
            field=models.CharField(blank=True, choices=[('', '—'), ('dark', 'Dark theme'), ('light', 'Light theme')], default='', help_text='When set, this sketch is the home hero background for that theme.', max_length=10),
        ),
        migrations.AlterField(
            model_name='sketch',
            name='is_home_background',
            field=models.BooleanField(default=False, help_text='Use this sketch as an animated home-page background (see theme).'),
        ),
    ]
