# Generated by Django 5.2.14 on 2026-07-29 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sketches", "0010_sketch_landing_ide_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="sketch",
            name="app_icon",
            field=models.ImageField(
                blank=True,
                help_text="Square app-style icon for mobile gallery lists (recommended 192×192).",
                null=True,
                upload_to="app_icons/",
            ),
        ),
    ]
