# Generated by Django 6.0.6 on 2026-08-12 17:29
#
# MySQL note: older PythonAnywhere DBs still have sketches_sketch.id as INT while
# Django 6 emits BIGINT FKs (DEFAULT_AUTO_FIELD=BigAutoField). That causes
# OperationalError 3780 on CreateModel. The RunPython below widens Sketch PK +
# referencing FKs to BIGINT on MySQL only (no-op on SQLite).

import django.db.models.deletion
import sketches.models
from django.db import migrations, models


def _mysql_on_delete_clause(delete_rule: str) -> str:
    rule = (delete_rule or "RESTRICT").upper()
    if rule == "CASCADE":
        return "ON DELETE CASCADE"
    if rule == "SET NULL":
        return "ON DELETE SET NULL"
    if rule == "SET DEFAULT":
        return "ON DELETE SET DEFAULT"
    if rule in ("RESTRICT", "NO ACTION"):
        return "ON DELETE RESTRICT"
    return "ON DELETE RESTRICT"


def _mysql_widen_sketch_pk_to_bigint(schema_editor):
    """Align sketches_sketch.id (+ inbound FKs) with BigAutoField before SketchMedia."""
    connection = schema_editor.connection
    if connection.vendor != "mysql":
        return

    with connection.cursor() as cursor:
        # Leftover from a failed 0017 that created the table then failed on the FK.
        cursor.execute("DROP TABLE IF EXISTS sketches_sketchmedia")

        cursor.execute(
            """
            SELECT COLUMN_TYPE
            FROM information_schema.COLUMNS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'sketches_sketch'
              AND COLUMN_NAME = 'id'
            """
        )
        row = cursor.fetchone()
        if not row:
            return
        column_type = (row[0] or "").lower()
        # Already bigint (signed or unsigned) — nothing to do.
        if column_type.startswith("bigint"):
            return

        cursor.execute(
            """
            SELECT
                kcu.CONSTRAINT_NAME,
                kcu.TABLE_NAME,
                kcu.COLUMN_NAME,
                rc.DELETE_RULE
            FROM information_schema.KEY_COLUMN_USAGE AS kcu
            JOIN information_schema.REFERENTIAL_CONSTRAINTS AS rc
              ON rc.CONSTRAINT_SCHEMA = kcu.CONSTRAINT_SCHEMA
             AND rc.CONSTRAINT_NAME = kcu.CONSTRAINT_NAME
             AND rc.TABLE_NAME = kcu.TABLE_NAME
            WHERE kcu.TABLE_SCHEMA = DATABASE()
              AND kcu.REFERENCED_TABLE_NAME = 'sketches_sketch'
              AND kcu.REFERENCED_COLUMN_NAME = 'id'
            """
        )
        fks = list(cursor.fetchall())

        for constraint_name, table_name, _column_name, _delete_rule in fks:
            cursor.execute(
                f"ALTER TABLE `{table_name}` DROP FOREIGN KEY `{constraint_name}`"
            )

        widen_columns = {
            (table_name, column_name)
            for _constraint, table_name, column_name, _delete_rule in fks
        }
        for table_name, column_name in (
            ("sketches_sketchasset", "sketch_id"),
            ("sketches_sketch_tags", "sketch_id"),
            ("sketches_sketch", "forked_from_id"),
        ):
            cursor.execute(
                """
                SELECT COUNT(*)
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            if cursor.fetchone()[0]:
                widen_columns.add((table_name, column_name))

        for table_name, column_name in sorted(widen_columns):
            cursor.execute(
                """
                SELECT IS_NULLABLE, COLUMN_TYPE
                FROM information_schema.COLUMNS
                WHERE TABLE_SCHEMA = DATABASE()
                  AND TABLE_NAME = %s
                  AND COLUMN_NAME = %s
                """,
                [table_name, column_name],
            )
            meta = cursor.fetchone()
            if not meta:
                continue
            is_nullable, child_type = meta
            if (child_type or "").lower().startswith("bigint"):
                continue
            null_sql = "NULL" if is_nullable == "YES" else "NOT NULL"
            cursor.execute(
                f"ALTER TABLE `{table_name}` "
                f"MODIFY `{column_name}` BIGINT {null_sql}"
            )

        cursor.execute(
            "ALTER TABLE `sketches_sketch` "
            "MODIFY `id` BIGINT NOT NULL AUTO_INCREMENT"
        )

        for constraint_name, table_name, column_name, delete_rule in fks:
            on_delete = _mysql_on_delete_clause(delete_rule)
            cursor.execute(
                f"ALTER TABLE `{table_name}` "
                f"ADD CONSTRAINT `{constraint_name}` "
                f"FOREIGN KEY (`{column_name}`) REFERENCES `sketches_sketch` (`id`) "
                f"{on_delete}"
            )


def widen_sketch_pk_for_mysql(apps, schema_editor):
    _mysql_widen_sketch_pk_to_bigint(schema_editor)


def noop_reverse(apps, schema_editor):
    # Do not shrink BIGINT back to INT — unsafe if SketchMedia already exists.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("sketches", "0016_sketch_scoreboard_slug"),
    ]

    operations = [
        migrations.RunPython(widen_sketch_pk_for_mysql, noop_reverse),
        migrations.CreateModel(
            name="SketchMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filename",
                    models.CharField(help_text="e.g. cat.png", max_length=200),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=500,
                        upload_to=sketches.models.sketch_media_upload_to,
                    ),
                ),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                (
                    "kind",
                    models.CharField(
                        choices=[("image", "Image"), ("audio", "Audio")],
                        max_length=20,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "sketch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="sketches.sketch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sketch media",
                "verbose_name_plural": "Sketch media",
                "ordering": ["order", "filename"],
                "unique_together": {("sketch", "filename")},
            },
        ),
    ]
