# Generated by Django 6.0.6 on 2026-08-12 17:29

import django.db.models.deletion
import sketches.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0016_sketch_scoreboard_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SketchMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(help_text='e.g. cat.png', max_length=200)),
                ('file', models.FileField(max_length=500, upload_to=sketches.models.sketch_media_upload_to)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sketch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='sketches.sketch')),
            ],
            options={
                'verbose_name': 'Sketch media',
                'verbose_name_plural': 'Sketch media',
                'ordering': ['order', 'filename'],
                'unique_together': {('sketch', 'filename')},
            },
        ),
    ]
