# Generated by Django 6.0.6 on 2026-08-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sketches', '0017_sketchmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sketchmedia',
            name='kind',
            field=models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('font', 'Font')], max_length=20),
        ),
    ]
