"""
Django settings for sketch_gallery project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

_RUNNING_TESTS = len(sys.argv) >= 2 and sys.argv[1] == "test"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-y^(9595rquvd0y4og&zaw3i6j*hebcs2!=q^16lriquwg-gm92",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "true").lower() in ("true", "1", "yes")

_allowed_hosts = os.environ.get("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [host.strip() for host in _allowed_hosts.split(",") if host.strip()]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "")
CSRF_TRUSTED_ORIGINS = [
    origin.strip() for origin in _csrf_origins.split(",") if origin.strip()
]
if DEBUG:
    for origin in ("http://localhost:5173", "http://127.0.0.1:5173"):
        if origin not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'sketches',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ROOT_URLCONF is set below after SPA_AT_ROOT

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'sketches' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sketches.context_processors.home_background_sketches',
            ],
        },
    },
]

WSGI_APPLICATION = 'sketch_gallery.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Vite React SPA build output (served at / when SPA_AT_ROOT)
SPA_DIR = BASE_DIR / "sketches" / "static" / "spa"
# Production default: SPA at /. Tests default to legacy HTML URLconf.
_SPA_DEFAULT = "false" if _RUNNING_TESTS else "true"
SPA_AT_ROOT = os.environ.get("SPA_AT_ROOT", _SPA_DEFAULT).lower() in ("true", "1", "yes")

LOGIN_URL = "/login" if SPA_AT_ROOT else "login"
LOGIN_REDIRECT_URL = "/account" if SPA_AT_ROOT else "account"
LOGOUT_REDIRECT_URL = "/" if SPA_AT_ROOT else "home"

ROOT_URLCONF = (
    "sketch_gallery.urls" if SPA_AT_ROOT else "sketch_gallery.urls_legacy"
)

# Browser cache for published sketch embed iframes (seconds).
PUBLISHED_EMBED_MAX_AGE = int(os.environ.get("PUBLISHED_EMBED_MAX_AGE", "300"))
HOME_BACKGROUND_EMBED_MAX_AGE = int(os.environ.get("HOME_BACKGROUND_EMBED_MAX_AGE", "86400"))

if not DEBUG:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }
    WHITENOISE_MAX_AGE = 60 * 60 * 24 * 30  # 30 days

SKETCH_PROJECTS_ROOT = BASE_DIR / 'sketch_projects'

# Auto-generated gallery thumbnails
SKETCH_THUMBNAIL_AUTO_GENERATE = os.environ.get(
    "SKETCH_THUMBNAIL_AUTO_GENERATE", "true"
).lower() in ("true", "1", "yes")
SKETCH_THUMBNAIL_SIZE = (1280, 800)  # 16:10 — matches gallery cards
SKETCH_THUMBNAIL_CARD_SIZE = (640, 400)
SKETCH_THUMBNAIL_BACKGROUND = (13, 13, 13)  # brand dark; avoids light letterbox edges
SKETCH_THUMBNAIL_WEBP_QUALITY = 80
SKETCH_THUMBNAIL_CAPTURE_TIMEOUT_MS = 15000
SKETCH_THUMBNAIL_SETTLE_MS = 2000

X_FRAME_OPTIONS = 'SAMEORIGIN'

SITE_NAME = os.environ.get("SITE_NAME", "sketches101")
SITE_URL = os.environ.get("SITE_URL", "http://127.0.0.1:8000")

# Google Identity Services (SPA ID-token → POST /api/auth/google/)
GOOGLE_OAUTH_CLIENT_ID = os.environ.get("GOOGLE_OAUTH_CLIENT_ID", "")

EMAIL_HOST = os.environ.get("EMAIL_HOST", "")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = int(os.environ.get("EMAIL_PORT", "587"))
    EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "true").lower() == "true"
    EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "false").lower() == "true"
    EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
    EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        EMAIL_HOST_USER or "noreply@sketchgallery.local",
    )
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    DEFAULT_FROM_EMAIL = os.environ.get(
        "DEFAULT_FROM_EMAIL",
        "noreply@sketchgallery.local",
    )
